version: '3'
services:
  redis-01:
    container_name: "redis-01"
    image: redis:6.2.7
    ports:
      - "6379:6379"
    command: "redis-server /etc/redis.conf"
    volumes:
      - "./data:/data/"
      - "./redis.conf:/etc/redis.conf"