version: '3.0'

services:
  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
    command: --config /oauth2-proxy.cfg
    ports:
      - 4180:4180/tcp
    hostname: oauth2-proxy
    volumes:
      - "./oauth2-proxy.cfg:/oauth2-proxy.cfg"
    restart: unless-stopped

  testapp:
    container_name: testapp
    build:
      context: ./express
    ports:
      - 3000:3000

  app1:
    container_name: app1
    build:
      context: ./app1
    ports:
      - 5001:5001

  app2:
    container_name: app2
    build:
      context: ./app2
    ports:
      - 5002:5002

  nginx:
    container_name: nginx
    image: nginx:1.18
    ports:
      - 80:80/tcp
    hostname: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
